# Uncomment this line to define a global platform for your project
platform :ios, '10.3'

target 'HoneyDew' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HoneyDew
  pod 'Firebase'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'GoogleSignIn'

  target 'HoneyDewTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'HoneyDewUITests' do
    inherit! :search_paths
    # Pods for testing
  end
end
